### ISSUE TITLE
AutosizeInputDirective::onLoad method should declare a parameter

### ISSUE THREAD

**Issue by amitport** [DesertFoxNV/ngx-autosize-input#3] opened 2018-01-14 08:36 UTC
when compiling with angular@5.2's fullTemplateTypeCheck, I get:

`Directive AutoSizeInputDirective, Expected 0 arguments, but got 1.`

According to https://github.com/angular/angular/issues/21329#issuecomment-355540967, the root cause is that https://github.com/DesertFoxNV/ngx-autosize-input/blob/master/src/autosize-input.directive.ts#L14 should declare it's parameters.

**Comment by joshuawwright** [comment] 2018-01-22 19:56
@amitport I believe I was missing the event parameter on the onInput event, I have updated the onInput code to the following:

` public onInput(event: any): void {
        this.adjustWidth();
    }`

I have pushed the updated code to npm: ngx-autosize-input 1.0.3

I will assume this issue is now fixed, and close it. However, if the fix did not work, please let me know and I will reopen the issue.

**Comment by brunoc-carneiro** [comment] 2018-10-01 08:12
Hi, 
I have the same issue with version 2.2.2.
`
Directive AutoSizeInputDirective, Expected 0 arguments, but got 1.
`
I am using latest angular.

**Comment by joshuawwright** [comment] 2018-10-03 16:32
@brunoc-carneiro what version of angular are you using?

**Comment by joshuawwright** [comment] 2018-10-03 16:50
@brunoc-carneiro I created a fresh 6.1.9 project, added the directive, and then tried ng serve and ng build. I was not able to replicate the issue. Please provide more detail if possible.

**Comment by brunoc-carneiro** [comment] 2018-10-04 12:41
I am using 6.1.5
It works fine when using it after building an app (hot reloading), but doesn't when I add the directive to an input before building it.

**Comment by joshuawwright** [comment] 2018-10-04 21:00
@brunoc-carneiro can you provide me steps to reproduce the error? Maybe show me how you are using the directive?

**Comment by joshuawwright** [comment] 2018-10-09 23:13
@brunoc-carneiro I would like to fix your issue, but since I can't replicate it, I am going to close the issue for now. I will be happy to re-open and fix the issue if you provide me with the steps required to reproduce the issue.

**Closed as completed by joshuawwright** 2018-10-09 23:13 UTC
Labels: bug

**Comment by anikets43** [comment] 2019-06-18 09:41
@DesertFoxNV 
Steps to reproduce
1. Enable `fullTemplateTypeCheck` in `tsconfig.json`
```"angularCompilerOptions": {
        "fullTemplateTypeCheck": true,
        "strictInjectionParameters": true
    }
```

2.  ` <input AutoSizeInput [minWidth]="300" [maxWidth]="500" [(ngModel)]="value" type="text" />`

3. Run `ng build --configuration production` with below config
``` 
       "optimization": true,
       "aot": true,
       "buildOptimizer": true,
````

![image](https://user-images.githubusercontent.com/7136799/59671466-5287af00-91db-11e9-8133-620815886e09.png)
